spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petplate?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10

logging:
  level:
    org.hibernate.SQL: debug
  #  org.hibernate.type: trace


jwt:
  token:
    secret: ${JWT_TOKEN_SECRET}